### PR TITLE
Feature/refactor 20200616

### PR DESCRIPTION
**Pull request by marlanperumal**
@hrudham @aquavitae I'd appreciate a code review on this please :)

Please note that this branch requires the latest version of the codenames-backend repo to run against

Changes as follows:
- Set up prettier to run with post-commit hook. I'm not precious about any particular code-style, I just want it all to be consistent, so happy to make changes to the config
- Extracted out all the major components to their own files and wherever possible moved state management to the lowest component possible
- There's still a little bit of passing props down but I think it's still simple enough that it doesn't require any sort of central state management solution
- The separate components should now be easy to move around if we want to change the layout especially for mobile friendliness
  - By that I mean they should still functionally work
  - The styling probably would still need a bit of tweaking - I'm sure it's possible to set that up better
- I also haven't yet made any attempt to consolidate the scss and styled components

### CODE REVIEW

**Comment by aquavitae** [comment]
Looks fine to me. I'm sure there's still more that can be done, but this is iterative.
* Regarding central state management, I'd avoid that as long as possible - it adds quite a bit of complexity, so only add it when the current setup gets complicated enough to warrent it. Which I doubt will ever happen in this project.
* scss vs styled components, I'd go with emotion :grin:

**Comment by marlanperumal** [comment]
Thanks David - agreed that I'd like to avoid CSM for as long as possible

I had a look at emotion and the API seems identical to styled components. If that's the case and we can just use it as a drop in replacement with some additional benefits, then that makes sense to do. Hilton can advise if it does the things he was struggling with in the current setup.

I was curious as to why a css framework would have their entire website in monochrome but then I saw the top banner...

**Comment by aquavitae** [comment]
Don't know what Hilton was stuggling with, but I've used emotion and it seems pretty comprehensive. It has a similar, but slightly more usable concept of styled components. Instead of `styled.div` followed by srting, the `styled` is a function that returns a css object (e.g. `{border: 0}`). The fact that it's a function makes it very easy to extend and include slightly more complicated logic.

**Comment by marlanperumal** [comment]
They seem to have converged. 

Styled Components provides a function-object [interface](https://styled-components.com/docs/advanced#style-objects) and Emotion provides a template literal [interface](https://emotion.sh/docs/styled)

Though I do see that emotion specifically calls out how to do [media queries](https://emotion.sh/docs/media-queries) which we couldn't find explicitly in Styled Components but I see no reason why it shouldn't be exactly the [same](https://jsramblings.com/how-to-use-media-queries-with-styled-components/)

To be honest I would probably actually prefer the object syntax instead of the template literals, and if you're already familiar with emotion then maybe it's the right call to move over while we're at it

**Comment by marlanperumal** [comment]
Yeah most of the discussion online says they're practically the same. The thing that might just swing it for me is [this point](https://spectrum.chat/styled-components/general/styled-components-vs-emotion~47206c1b-a688-424e-9e96-6f265993587e) that the css prop means you don't need to name everything! Apparently you can accomplish the same thing with styled components but I couldn't be bothered to set up the required babel config.

I guess that means Emotion it is :)

**Comment by aquavitae** [comment]
The css prop does work well, the only reason I moved away from it was that I liked keeping the layout and styling separate. But that's really a very minor stylistic opinion.

**Comment by hrudham** [comment]
> Don't know what Hilton was stuggling with, but I've used emotion and it seems pretty comprehensive.

To clarify things, I wasn't struggling; it was just a case of getting used to writing styling in components as opposed to having separate styling.

While frameworks like emotion can be very convenient from a coding perspective, I find there are still a few advantages to using separate style sheet. For example, you get to keep the "cascading" part of CSS, which you can lose with inline styles. I've found implementing a second or third theme later in development is also a lot easier when your style sheets are not coupled with the code (and I'm talking more than just colour changes in themes; think http://www.csszengarden.com stuff).

Transpilers like SASS make styling a breeze, and allow for sweaping changes once you start using it's mixins, functions and other language features. One thing that I find particularly useful are all the colour related tools: you can set a colour pallette up, and apply alpha transparency, darken, lighten, adjust hues, etc. based on it. And then if you change the pallette later, everything still works. You also gain nested styles: it always blows my mind that that wasn't part of the original CSS specification.

I seem to remember that when I first enountered inline-style frameworks like emotion, media query support was non-existent, and I admit I've never really gone back to see how things have changed. 

Having said that, neither approach is wrong: both have their pros and cons (and it's a long list on both sides). It's just about sticking to a single approach that solves all our problems, so that things are at least easy to understand and maintain.

**Comment by aquavitae** [comment]
I think emotion does all that, just via javascript code instead of SASS code, so they end up pretty much the same. I do agree about the inline styles, which is why I'm not a fan of the css prop. From what I've seen, emotion can now do everything SASS does, including media queries, colour tools (actually a separate lib), nesting, etc. Also, it avoids the headache of naming classes, which I'm terrible at. Oh, and emotion is pure js - I've had many headaches in the past trying to install and compile node-sass on less popular docker images behind a corporate firewall. Not something Marlan has to worry about though.

So really, what we're both saying, is either will work fine, as long as you don't use inline styles.

**Pull request merged**
